### ISSUE TITLE
Global Packs mod stop working when using Mob Armor Trims

### ISSUE THREAD

**Issue by ManoBambu** [Imajo24I/Mob-Armor-Trims-1.20.1#4] opened 2024-06-23 17:14 UTC
### Incompatible Mod

global_packs-quilt-1.19.4-1.16.1_quilt

### Issue

when launching "global_packs-quilt-1.19.4-1.16.1_quilt" with "mob_armor_trims-fabric-2.1.1", the global resourcepacks and global datapacks doesnt apply in game. the "global packs" mod doesnt appear on modmenu either. 

### Mod Setup

Minecraft 1.20.1 with Quilt Loader 0.26.0
Prism Launcher
LWJGL 3.3.2
Lots of addiotional mods. Like, 300 mods. If you want the complete list, just message me

### Additional Information

I installed like 10 new mods in my modpack, suddently global packs gone. Loaded the game without the 10 new mods, it worked. Then I was gona check with new mod was causing this. and BAM! First one I pick was armor trims, loaded the game with the remaining 9 new mods and it worked;

**Comment by Imajo24I** [comment] 2024-06-23 18:39
I'm unable to reproduce this issue. 
Try updating both Mob Armor Trims and Quilt Loader to the newest versions.
If the problem still occures, please send the `latest.log` file inside `.minecraft/logs`. The modlist is included in the log, so no need to send it manually.

**Comment by Imajo24I** [comment] 2024-07-06 10:17
Hey there, due to me not being able to reproduce this issue and no response, I'll close this issue.
If you're still encountering this issue, do the steps from above comment and reopen this issue.

**Comment by NyxBornee** [comment] 2024-09-09 06:39
I am having the same issue in 1.21 Fabric with only Mob Trims and Global Packs
Look at lines 63 and 66 to see how 2 packs are loaded without the mod but aren't loaded with Mob Trims
If I need to send any more info let me know
[With Trim.log](https://github.com/user-attachments/files/16926431/With.Trim.log)
[Without Trim.log](https://github.com/user-attachments/files/16926432/Without.Trim.log)

**Comment by Imajo24I** [comment] 2024-09-09 16:40
I have now been able to reproduce this, thanks for reporting!
I'll look into fixing this, although currently I have no idea why this happens.

**Comment by Imajo24I** [comment] 2024-10-04 13:01
Fixed in Mob Armor Trims 2.4.2.

**Closed as completed by Imajo24I** 2024-10-04 13:01 UTC
